#ifndef DEFS_H_
#define DEFS_H_

#define DEBUG_MODE

#define POWER_VOUT_SETPOINT 12.0
#define POWER_VIN_NOMINAL   48.0

#define POWER_VOUT_TOLERANCE 1.0
#define POWER_VIN_TOLERANCE  10.0

#define POWER_VOUT_RANGE_MIN 0.0
#define POWER_VOUT_RANGE_MAX 13.0

#define POWER_VIN_RANGE_MIN  0.0
#define POWER_VIN_RANGE_MAX  70.0

#define POWER_IOUT_RANGE_MIN 0.0
#define POWER_IOUT_RANGE_MAX 60.0

#define POWER_POUT_RANGE_MIN 0.0
#define POWER_POUT_RANGE_MAX 600.0

#endif /* DEFS_H_ */
